import Head from "next/head";
import React from "react";
import Link from "next/link";
import Skills from "../components";

export default function Home() {
  const experienceRef = React.useRef(null);
  const skillsRef = React.useRef(null);
  const educationRef = React.useRef(null);

  React.useEffect(() => {
    let observer;
    if (experienceRef.current && skillsRef.current) {
      const options = {
        threshold: 0.2,
      };
      observer = new IntersectionObserver((entries, observer) => {
        entries.forEach((entry) => {
          const navElement = document.querySelector(
            `a[href="/#${entry.target.id}"]`
          );
          if (
            entry.isIntersecting &&
            !navElement.classList.contains("text-gray-100")
          ) {
            navElement.classList.add("text-gray-100");
          } else if (
            !entry.isIntersecting &&
            navElement.classList.contains("text-gray-100")
          ) {
            navElement.classList.remove("text-gray-100");
          }
        });
      }, options);
      observer.observe(experienceRef.current);
      observer.observe(skillsRef.current);
    }
    return () => observer?.disconnect();
  }, [experienceRef, skillsRef]);

  return (
    <>
      <Head>
        <title>Simeon Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full min-h-screen font-sans bg-night">
        <div className="container px-6 py-4 mx-auto text-white md:py-8 md:px-14 lg:py-0 lg:flex">
          {/* ---------left--------- */}
          <div className="lg:w-1/3 lg:py-20 lg:h-screen lg:flex lg:flex-col lg:justify-between">
            {/* ------- hero -------- */}
            <div>
              <h1 className="mb-6 text-6xl font-semibold leading-tight">
                Hi, I'm Bamidele
              </h1>

              {/* ------- para -------- */}
              <p className="mb-6 leading-loose text-dawn">
                I came across software development totally out of curiosity, and
                since learning the power and freedom it gives, I fell in love
                and I have learnt a few things. I also apply my passion for
                developing products with Node.js and Modern Javascript Library
                and Frameworks.
                <span role="img" className="animate-pulse">
                  💓
                </span>
                .
              </p>
              {/* ------- para -------- */}
            </div>

            {/* ------- hero -------- */}

            {/* ----- tags ------- */}
            <div className="hidden text-gray-500 lg:block">
              <Link href={{ pathname: "/", hash: "experience" }}>
                <a className="inline-flex items-center w-full">
                  1.
                  <div className="w-1/4 h-0.5 bg-gray-500 mx-3"></div>
                  Experience
                </a>
              </Link>

              <Link href={{ pathname: "/", hash: "skills" }}>
                <a className="inline-flex items-center w-full">
                  2.
                  <div className="w-1/4 h-0.5 bg-gray-500 mx-3"></div>
                  Skills
                </a>
              </Link>
            </div>
            {/* ----- tags ------- */}

            {/* ------------- handlers ------------- */}
            <div className="flex items-center mb-14 lg:block">
              {/* ------- image ------- */}
              <img
                src="/mine.jfif"
                className="w-40 h-40 rounded-full lg:w-16 lg:h-16 lg:mb-6"
                alt="profile image"
              />
              {/* ------- image ------- */}

              {/* ----- links ------ */}
              <div className="flex items-center ml-12 space-x-6 lg:ml-0 lg:flex-col lg:items-start lg:space-y-4 lg:space-x-0">
                {/* -------- linkedIn ------------ */}
                <a
                  className="flex items-baseline md:space-x-3 hover:text-gray-500"
                  href="https://www.linkedin.com/in/bamidele-simeon-406a10181/"
                  rel="noopener"
                  target="_blank"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 310 310"
                    aria-hidden="true"
                    className="w-6 h-6 fill-current md:w-4 md:h-4"
                  >
                    <title>LinkedIn</title>
                    <path d="M72.16 99.73H9.927a5 5 0 00-5 5v199.928a5 5 0 005 5H72.16a5 5 0 005-5V104.73a5 5 0 00-5-5zM41.066.341C18.422.341 0 18.743 0 41.362 0 63.991 18.422 82.4 41.066 82.4c22.626 0 41.033-18.41 41.033-41.038C82.1 18.743 63.692.341 41.066.341zM230.454 94.761c-24.995 0-43.472 10.745-54.679 22.954V104.73a5 5 0 00-5-5h-59.599a5 5 0 00-5 5v199.928a5 5 0 005 5h62.097a5 5 0 005-5V205.74c0-33.333 9.054-46.319 32.29-46.319 25.306 0 27.317 20.818 27.317 48.034v97.204a5 5 0 005 5H305a5 5 0 005-5V194.995c0-49.565-9.451-100.234-79.546-100.234z" />
                  </svg>
                  <span className="hidden md:block">LinkedIn</span>
                  <div className="hidden md:block">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      stroke="currentColor"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      viewBox="0 0 12 12"
                      aria-hidden="true"
                      className="flex-none w-3 h-3 stroke-current"
                    >
                      <title>External link icon</title>
                      <path d="M10.976 1.193A.314.314 0 0010.687 1H6.312a.313.313 0 000 .625h3.62L5.467 6.091a.313.313 0 00.443.442l4.466-4.466v3.62a.313.313 0 00.625 0V1.313a.328.328 0 00-.024-.119z"></path>
                      <path d="M3.5 1v.625H2.25a.625.625 0 00-.625.625v7.5c0 .345.28.625.625.625h7.5c.345 0 .625-.28.625-.625V8.5H11v1.875c0 .345-.28.625-.625.625h-8.75A.625.625 0 011 10.375v-8.75C1 1.28 1.28 1 1.625 1H3.5z"></path>
                    </svg>
                  </div>
                </a>
                {/* -------- linkedIn ------------ */}
              </div>
              {/* ----- links ------ */}
            </div>
            {/* --------- handlers----------- */}
          </div>
          {/* --------- left --------- */}

          {/* ====================================================== */}

          {/* ---------- right --------- */}
          <div className="flex-1 lg:py-20 lg:h-screen lg:overflow-y-scroll scrollbar-hide">
            {/* ------ experience ------- */}
            <div id="experience" className="pt-14" ref={experienceRef}></div>
            <h1 className="lg:hidden">
              Experience{" "}
              <div className="h-0.5 w-1/2 bg-dawn rounded-full"></div>
            </h1>

            <div className="flex-col items-center mb-20 space-y-14 lg:flex lg:mb-24">
              {/* ----- cloud services---- */}
              <div className="relative p-6 my-3 text-gray-200 transition duration-300 transform rounded-lg bg-dusk lg:w-2/3 lg:hover:scale-110">
                <img
                  src="/cloud.jpg"
                  className="absolute top-0 right-0 transform -translate-x-5 -translate-y-8 shadow h-14 w-14 md:h-20 md:w-20"
                />
                <p className="text-xl font-medium">
                  <a
                    href="https://next-cloud-xi.vercel.app/"
                    target="_blank"
                    className="text-blue-400 underline"
                  >
                    Cloud Services UI
                  </a>
                </p>
              </div>
              {/* ----- cloud services ---- */}

              {/* ----- uber clone ---- */}
              <section className="relative p-6 my-3 text-gray-200 transition duration-300 transform rounded-lg bg-dusk lg:w-2/3 lg:hover:scale-110">
                <img
                  src="/uber.png"
                  className="absolute top-0 right-0 transform -translate-x-5 -translate-y-8 shadow w-18 h-14 md:h-20 md:w-22"
                />
                <p className="text-xl font-medium">
                  <a
                    href="https://bounceshare.com/"
                    target="_blank"
                    className="text-white underline"
                  >
                    Uber Web 3.0
                  </a>
                </p>
              </section>
              {/* ----- uber clone ---- */}

              {/* ----- real estate app ---- */}
              <section className="relative p-6 my-3 text-gray-200 transition duration-300 transform rounded-lg bg-dusk lg:w-2/3 lg:hover:scale-110">
                <img
                  src="/Real-estate.jpg"
                  className="absolute top-0 right-0 transform -translate-x-5 -translate-y-8 shadow w-18 h-14 md:h-20 md:w-22 bg-white p-2 rounded-lg"
                />
                <p className="text-xl font-medium">
                  <a
                    href="https://www.quest-global.com/"
                    target="_blank"
                    className="text-orange-700 underline"
                  >
                    Real Estate App
                  </a>
                </p>
              </section>
              {/* ----- real estate app ---- */}

              {/* ----- real estate app ---- */}
              <section className="relative p-6 my-3 text-gray-200 transition duration-300 transform rounded-lg bg-dusk lg:w-2/3 lg:hover:scale-110">
                <img
                  src="/Real-estate.jpg"
                  className="absolute top-0 right-0 transform -translate-x-5 -translate-y-8 shadow w-18 h-14 md:h-20 md:w-22 bg-white p-2 rounded-lg"
                />
                <p className="text-xl font-medium">
                  <a
                    href="https://www.quest-global.com/"
                    target="_blank"
                    className="text-orange-700 underline"
                  >
                    Real Estate App
                  </a>
                </p>
              </section>
              {/* ----- real estate app ---- */}
            </div>
            {/* ------ experience ------- */}
            {/* ------ skills ------- */}
            <h1 className="lg:hidden">
              Skills <div className="h-0.5 w-1/2 bg-dawn rounded-full"></div>
            </h1>
            <div id="skills" ref={skillsRef}></div>
            <Skills />
            {/* ------ skills ------- */}

            {/* ------ contact me ------- */}
            <h1 className="lg:hidden">
              Contact me{" "}
              <div className="h-0.5 w-1/2 bg-dawn rounded-full"></div>
            </h1>
            <div className="pb-14">
              <p className="text-gray-400">
                {" "}
                I'm open for new opportunities and requests.
              </p>
              <p className="leading-loose text-2xl text-white">
                bamidelesimeon05@gmail.com
              </p>
            </div>
            {/* ------ contact me ------- */}
          </div>
          {/* ---------- right --------- */}
        </div>
      </div>
    </>
  );
}
